<script src="{{asset('js/jclocks.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/crouseljs/owl.carousel.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/homepage.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/marquee.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/popper.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/slick.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/custom.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/jClocksGMT.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/jquery.rotate.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/jquery.countup.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/jquery.waypoints.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/ajax.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/jquery.validate.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/additional-methods.min.js')}}?t=<?php echo time();?>"></script>
<script src="{{asset('js/recaptcha_api.js')}}?t=<?php echo time();?>"></script>