name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:          
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Deploy to my EC2 instance
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}            
          remote_path: ${{ secrets.TARGET_DIR }}            
          sftpArgs: '-o ConnectTimeout=5'
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          # key: ${{ secrets.EC2_SSH_KEY }}
          password: ${{ secrets.PASSWORD }}            
          script: |
            cd $TARGET_DIR
            chmod 777 -R /home/plutustec-web/htdocs/web.plutustec.com/storage/
            chmod 777 -R /home/plutustec-web/htdocs/web.plutustec.com/bootstrap/
